environment: PROD

server:
  port: 7070

spring:
  application:
    name: LPR-Service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33244/foxtail_preview?useUnicode=true&useSSL=false
    name: root
    password: 1qazXSW@
  redis:
    host: localhost
    port: 6379
    database: 0

mybatis:
  check-config-location: false
