environment: DEV

server:
  port: 9090

spring:
  application:
    name: LPR-Service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33244/foxtail_preview?useUnicode=true&useSSL=false
    name: root
    password: 1qazXSW@
  session:
    redis:
      namespace: spring:session
  redis:
    host: localhost
    port: 6379
    ssl: false
#    password: 1234567890
#    url: redis://user:password@example.com:6379
logging:
  level: DEBUG

mybatis:
  check-config-location: false

